Hr the captains room
aepaysinger/code-challenges pull request #19
Opened 2022-07-15 19:38 UTC by aepaysinger

2022-07-15 23:29 UTC, W-Ely requested changes
Include the tests :-]

2022-07-16 13:54 UTC, aepaysinger commented
i thought i did the tests!!!! i guess i somehow lost them lol but ill redo that part. my bad!

2022-07-16 20:34 UTC, W-Ely approved these changes

2022-07-16 20:34 UTC, W-Ely commented on tests/hacker_rank/test_the_captains_room.py
> +    expected = '8'
Rerun black and commit.

2022-07-17 23:53 UTC, merged