Cw youre a square
aepaysinger/code-challenges pull request #27
Opened 2022-08-11 18:34 UTC by aepaysinger

2022-08-11 22:13 UTC, W-Ely submitted a review, later dismissed
Probably this is meant to check for _perfect_ squares.

You have three code paths and only 2 tests.  What would the last test look like?

2022-08-12 00:01 UTC, aepaysinger commented
it would be for less than 0

2022-08-12 12:32 UTC, W-Ely commented on code_challenges/code_wars/youre_a_square.py
> +    # fun things
Stray comment

2022-08-22 14:23 UTC, W-Ely requested changes
I didn't read the whole commit.  I see now it is a very long message.

2022-09-29 13:51 UTC, aepaysinger commented
i think this is cleaned up now

2022-09-29 16:07 UTC, W-Ely approved these changes

2022-09-29 17:55 UTC, merged